#!/usr/bin/env bash
set -euo pipefail

# Generate infra/compose.yml for a libp2p shardd cluster.
#
# Topology: N nodes on an internal bridge network, each paired with its
# own Postgres container (protocol §6.1 — no shared storage). Node1 is
# the bootstrap seed; all other nodes dial it via libp2p multiaddr.
# A shardd-gateway instance exposes the public HTTP API, and Caddy fronts it.
#
# Usage: ./generate-compose.sh [node_count] [output_path]

NODE_COUNT="${1:-3}"
OUTPUT="${2:-$(dirname "$0")/compose.yml}"

LP2P_BASE=4000   # libp2p TCP: 4001, 4002, ... (internal to the compose network)

cat > "$OUTPUT" <<'HEADER'
# Generated by infra/generate-compose.sh — do not edit by hand.
# Re-run the script with a different NODE_COUNT to resize the cluster.

x-pg-env: &pg-env
  POSTGRES_DB: shardd
  POSTGRES_USER: shardd
  POSTGRES_PASSWORD: shardd

x-pg-healthcheck: &pg-healthcheck
  test: ["CMD-SHELL", "pg_isready -U shardd"]
  interval: 2s
  retries: 20

services:
HEADER

# Per-node Postgres instances.
for i in $(seq 1 "$NODE_COUNT"); do
    cat >> "$OUTPUT" <<EOF
  db-node${i}:
    image: postgres:17-alpine
    container_name: shardd-db-node${i}
    environment: *pg-env
    healthcheck: *pg-healthcheck
    volumes:
      - node${i}_db:/var/lib/postgresql/data
    networks: [shardnet]
    restart: unless-stopped

EOF
done

# Node services.
for i in $(seq 1 "$NODE_COUNT"); do
    lp2p_port=$((LP2P_BASE + i))

    # Node1 is the seed (no bootstrap). All others dial node1.
    if [ "$i" -eq 1 ]; then
        bootstrap_line=""
        seed_depends=""
    else
        bootstrap_line="      - --bootstrap=/dns4/shardd-node1/tcp/$((LP2P_BASE + 1))"
        seed_depends="      node1: { condition: service_started }"
    fi

    cat >> "$OUTPUT" <<EOF
  node${i}:
    image: shardd-node:latest
    container_name: shardd-node${i}
    command:
      - --host=0.0.0.0
      - --libp2p-port=${lp2p_port}
      - --advertise-addr=/dns4/shardd-node${i}/tcp/${lp2p_port}
      - --database-url=postgres://shardd:shardd@db-node${i}/shardd
EOF
    [ -n "$bootstrap_line" ] && echo "$bootstrap_line" >> "$OUTPUT"
    cat >> "$OUTPUT" <<EOF
    depends_on:
      db-node${i}: { condition: service_healthy }
EOF
    [ -n "$seed_depends" ] && echo "$seed_depends" >> "$OUTPUT"
    cat >> "$OUTPUT" <<EOF
    networks: [shardnet]
    restart: unless-stopped

EOF
done

# Gateway + Caddy reverse proxy.

cat >> "$OUTPUT" <<EOF
  gateway:
    image: shardd-gateway:latest
    container_name: shardd-gateway
    command:
      - --host=0.0.0.0
      - --port=8080
      - --bootstrap-peer=/dns4/shardd-node1/tcp/$((LP2P_BASE + 1))
    depends_on:
EOF
for i in $(seq 1 "$NODE_COUNT"); do
    echo "      node${i}: { condition: service_started }" >> "$OUTPUT"
done
cat >> "$OUTPUT" <<EOF
    networks: [shardnet]
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    container_name: shardd-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      gateway: { condition: service_started }
    networks: [shardnet]
    restart: unless-stopped

networks:
  shardnet:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
EOF
for i in $(seq 1 "$NODE_COUNT"); do
    echo "  node${i}_db:" >> "$OUTPUT"
done

echo "Generated $OUTPUT — ${NODE_COUNT} nodes, gateway on 8080, libp2p ${LP2P_BASE}+N"
